[FEAT]: Implement Backend API for Squeeze Page
hngprojects/hng_boilerplate_java_web pull request #128
Opened 2024-07-24 21:22 UTC by Fifetoyi

## Description:
Develop the API endpoint for the Squeeze Page.

## Purpose:
Provides a backend service that allows us collect the user email, store in the database and send a template to the user.

## Requirements:

- [x] Develop a RESTful API endpoint to handle POST requests.
- [x] Validate and verify incoming user data.
- [x] Store user information securely in the database.
- [x] Return appropriate response.
- [x] Handle errors and return appropriate status codes.
- [x] Send template to a specified email address using an email service (e.g., SendGrid, SMTP).

## Acceptance Criteria:
- The page should be accessible at `/api/v1/squeeze`.
- The endpoint should accept HTTP POST requests.

### Squeeze Form Submission:

- Endpoint: POST `/api/v1/squeeze`
- Request Body: 
```
{
  "email": "user@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "phone": "08098761234",
  "location": "Lagos, Nigeria",
  "job_title": "Software Engineer",
  "company": "X-Corp",
  "interests": ["Web Development", "Cloud Computing"],
  "referral_source": "LinkedIn"
}
```
- Validation: Ensure all fields are required and the email is in the correct format.
- Response (Success): 
```
{
  "message": "Your request has been received. You will get a template shortly."
}
```
- Response (Error): 
```
{
  "message": "Failed to submit your request",
  "status_code": 400
}
```
## Tasks:

- [x] Create an endpoint (POST `/api/v1/squeeze`) to handle contact form submissions.
- [x] Validate user input on the server side.
- [x] Securely store user information in the database.
- [x] Implement error handling and return appropriate status codes.
- [x] Write unit tests for contact form submission and data validation.
- [x] Write integration tests for confirmation of requests.

## Testing:

- Write unit tests for backend validation and data handling.
- Write integration tests for the end-to-end contact form submission process.
- Perform security testing to ensure data protection and compliance.
- Test various scenarios for form submissions (e.g., successful, invalid data, server errors).

## Expected Outcome:
A secure and efficient API endpoint that can receive user email, store it in the database, and confirm the user's request.
The API endpoint allows users to submit a request via the "Squeeze" form, and ensures the template is sent to the appropriate email address.

## Labels
feature

2024-07-24 22:14 UTC, Olaoluwa22 approved these changes
This looks good to me. Approved

2024-07-24 22:14 UTC, lurldgbodex commented
LGTM

2024-07-24 22:16 UTC, lurldgbodex submitted a review, later dismissed

2024-07-25 00:11 UTC, Am0du requested changes
The DTO's should be in a DTO package just for clarity

2024-07-25 00:11 UTC, Am0du commented on src/main/java/hng_java_boilerplate/squeeze/util/ResponseMessage.java
This could be in a dto package

2024-07-25 00:11 UTC, Am0du commented on src/main/java/hng_java_boilerplate/squeeze/util/ValidationErrorResponse.java
This could be placed in a dto package

2024-07-25 00:23 UTC, Fifetoyi commented on src/main/java/hng_java_boilerplate/squeeze/util/ResponseMessage.java
Fixed

2024-07-25 00:23 UTC, Fifetoyi commented on src/main/java/hng_java_boilerplate/squeeze/util/ValidationErrorResponse.java
Fixed

2024-07-27 11:25 UTC, lurldgbodex commented
resolve your conflict

2024-07-28 11:34 UTC, closed without merging