feat: Optional Two-Factor Authentication (2FA) using Time-based OTP
hngprojects/hng_boilerplate_java_web pull request #150
Opened 2024-07-25 09:00 UTC by ZainabAlayande

## How should this be manually tested?

- Try accessing all routes as an authorized user (Bearer Token)
- The expected results is to get a 200 successful
- Error response: 401 unauthorized

## Checklist of what you did
- Implemented 2fa option for additional layer of security (using user's current password for validity)
- Added the option to verify and confirm 2fa option 
- Option to disable 2fa
- Option to generate recovery codes for user who enabled 2fa

## Reference Issue
[https://github.com/hngprojects/hng_boilerplate_java_web/issues/120]()

2024-07-25 09:20 UTC, Fifetoyi commented on src/main/java/hng_java_boilerplate/user/controller/TwoFactorAuthController.java
> +    @Autowired
use constructor injection

2024-07-25 09:23 UTC, Fifetoyi commented on src/main/java/hng_java_boilerplate/user/serviceImpl/TwoFactorAuthServiceImpl.java
> +        System.out.println("logged in person == " + loggedInUser);
you can use a logger here instead of println

2024-07-25 09:27 UTC, Fifetoyi commented on src/main/java/hng_java_boilerplate/util/TwoFactorAuthUtils.java
> +//    public String storeQRCodeImage(byte[] qrCodeBytes, String username) throws IOException {
remove comments if not needed

2024-07-25 09:32 UTC, Fifetoyi commented on src/main/resources/application.properties
The app.prop file should not be tampered with. You can edit to make your service on your local but you should not push any changes upstream

2024-07-25 09:33 UTC, Fifetoyi commented on src/main/resources/db/migration/V2__alter_products_table_schema.sql
You shouldn't edit any of the schema files simply version yours and push that. Revert this

2024-07-25 09:36 UTC, Fifetoyi commented on src/test/java/hng_java_boilerplate/twoFA/TwoFAAuthTest.java
include e2e tests

2024-07-25 09:37 UTC, Fifetoyi requested changes
Cleanup required

2024-07-25 10:57 UTC, ZainabAlayande commented
Changes effected

2024-07-25 11:13 UTC, Am0du submitted a review, later dismissed

2024-07-25 11:13 UTC, Fifetoyi commented on src/main/resources/db/migration/V6__add_two_fa_columns_and_backup_codes_table.sql
use one sql file for your updates

2024-07-25 11:14 UTC, Am0du commented
@Fifetoyi it looks good but take a look also

2024-07-25 11:14 UTC, Fifetoyi commented on src/main/resources/db/migration/V1__init_database.sql
file tampered with. rollback to previous state

2024-07-25 11:16 UTC, Fifetoyi commented on src/main/resources/db/migration/V6__add_two_fa_columns_and_backup_codes_table.sql
> +                                     user_id VARCHAR(255) NOT NULL,
fix tabbing

2024-07-25 12:07 UTC, Fifetoyi commented
LGTM

2024-07-25 12:07 UTC, Fifetoyi approved these changes
LGTM

2024-07-27 18:34 UTC, Am0du commented
@lurldgbodex Please review

2024-07-27 20:59 UTC, lurldgbodex commented
Your code is failing build.

2024-07-28 17:01 UTC, lurldgbodex commented on src/main/resources/db/migration/V7__add_two_fa_and_secret_key_col.sql
> +-- V6__add_two_fa_columns_and_backup_codes_table.sql
update the migration version. there is a V7 in the database already

2024-07-28 17:02 UTC, lurldgbodex commented on src/main/resources/application.properties
> +
remove the application.properties file

2024-07-28 17:03 UTC, lurldgbodex requested changes
check the comments and make changes accordingly

2024-07-28 22:47 UTC, Fifetoyi approved these changes
lgtm

2024-07-29 06:36 UTC, lurldgbodex commented on src/main/resources/db/migration/V3__update_users_and_related_tables.sql
> +ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
do edit the existing migration file. It will crash the server

2024-07-29 08:35 UTC, merged