Feat: Endpoints for Fetch Product Stock
hngprojects/hng_boilerplate_java_web pull request #154
Opened 2024-07-25 09:47 UTC by Neche-Stephen

### How should this be manually tested?
---

Access the GET /api/v1/products/:productId/stock endpoint with a valid productId.
• Expected response are the required fields in JSON format. 
```json
{
  "productId": "12345",
  "currentStock": 100,
  "lastUpdated": "2024-07-18T10:00:00Z"
}
```
Access the GET /api/v1/products/:productId/stock endpoint with an invalid productId.
• Expected response is an appropriate error message and status code.
```json
{
"statusCode": 400,
"message": "Bad Request"
}
```

### Checklist of what you did
---

- [x] Implemented a functional GET /api/v1/products/:productId/stock endpoint.
- [x] Ensured that the endpoints return the required fields in JSON format.
- [x] Ensured proper error handling mechanisms are in place.

### Reference Issue
---

[FEAT]: Endpoint for Fetch Product Stock ([#284](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/284))

2024-07-25 09:49 UTC, Fifetoyi commented on Contributors.md
not needed

2024-07-25 09:51 UTC, Fifetoyi commented on pom.xml
there is already a flyway plugin in the codebase

2024-07-27 10:37 UTC, Neche-Stephen commented on Contributors.md
Removed

2024-07-27 10:38 UTC, Neche-Stephen commented on pom.xml
I have removed mine

2024-07-27 10:38 UTC, Neche-Stephen commented on pom.xml
> +					<user>postgres</user>
Removed as well.

2024-07-28 16:58 UTC, lurldgbodex commented on src/main/resources/db/migration/V7__alter_products_table_schema.sql
> +ALTER TABLE products
There is a version 7 of the migration file. update your version

2024-07-28 16:59 UTC, lurldgbodex requested changes
update your migration version

2024-07-31 17:57 UTC, closed without merging