Feat: Delete Organisation
hngprojects/hng_boilerplate_java_web pull request #167
Opened 2024-07-25 23:10 UTC by IgweWisdomJaminel

# Add Organisation Deletion Endpoint

## Description

This pull request adds an API endpoint to handle the deletion of an organization. The endpoint validates the organization ID and updates the specified organization's `deleted` attribute to `true` in the database upon successful validation.

## GitHub Issue: Organization Deletion Endpoint

## Acceptance Criteria

- **Endpoint**: The endpoint is accessible at `/api/v1/organizations/:org_id`.
- **HTTP Method**: The endpoint accepts HTTP DELETE requests.
- **Authentication**: The endpoint is protected and requires authentication.
- **Ownership Check**: The endpoint verifies that the user hitting the endpoint is the owner of the organization.
- **Authorization Header**: Requests to the endpoint include a valid authentication token in the `Authorization` header (e.g., `Authorization: Bearer <token>`).
- **Database Update**: Upon successful validation of the organization ID, the organization is marked as deleted by changing the `deleted` attribute in the database to `true`.
- **Data Integrity**: All related data to the organization remains intact.

## How to Test Manually

### Prerequisites
- Ensure you have the latest code from the `main` branch.
- Ensure your environment variables for database and authentication are set correctly.

### Steps to Test
1. **Clone the repository**: `git clone <repository-url>`
2. **Checkout to the new branch**: `git checkout <your-branch-name>`
3. **Install dependencies**: `npm install`
4. **Run the application**: `npm start`
5. **Authenticate and obtain a valid token**: Use the login endpoint to get a token.
6. **Issue a DELETE request** to the endpoint:
    - Use a tool like Postman or curl:
      ```
      DELETE /api/v1/organizations/<org_id>
      Content-Type: application/json
      Authorization: Bearer <token>
      ```
    - Replace `<org_id>` with a valid organization ID and `<token>` with your authentication token.
7. **Verify the responses**:
    - For a valid request, expect a **204 No Content** status.
    - For an invalid organization ID format, expect a **400 Bad Request** status.
    - For a non-existent organization ID, expect a **404 Not Found** status.
    - For unauthorized deletion attempt, expect a **401 Unauthorized** status.

### Expected Outcomes
- **204 No Content**: The organization is marked as deleted.
- **400 Bad Request**: Invalid organization ID format.
- **404 Not Found**: Invalid organization ID.
- **401 Unauthorized**: User not authorized to delete this organization.

## Checklist

- [x] Developed server-side logic to handle organization deletion requests.
- [x] Validated and sanitized incoming organization ID data.
- [x] Validated that the user deleting the organization is the owner.
- [x] Changed the specified organization's `deleted` attribute to `true` in the database upon successful validation.
- [x] Maintained data integrity by keeping all related data of the specified organization intact.
- [x] Wrote unit tests to ensure the organization deletion endpoint validates input correctly and removes the organization from the system.
- [x] Tested various scenarios for submitting the organization ID (e.g., valid ID, non-existent ID, malformed ID, etc.).
- [x] Verified that all unit tests pass.
- [x] Ensured the code follows the project's style guidelines.
- [x] Removed all console logs and comments.
- [x] Updated the documentation as necessary.
- [x] Informed relevant stakeholders of the changes.

2024-07-26 15:42 UTC, lurldgbodex commented
This is a java repo. Why do you have npm install?

2024-07-26 16:04 UTC, IgweWisdomJaminel commented
Changed 🫣

2024-07-26 23:09 UTC, lurldgbodex commented
please resolve your conflicts

2024-07-27 02:33 UTC, IgweWisdomJaminel commented
Done My boss The conflict was application.properties someone deleted it and I think there was an update to the dockerfile

2024-07-27 11:06 UTC, lurldgbodex commented
LGTM

2024-07-27 23:02 UTC, Am0du requested changes
Implement that change and we're good

2024-07-28 18:07 UTC, lurldgbodex commented on src/main/resources/application.properties
> +
remove the application.properties file

2024-08-02 02:53 UTC, closed without merging