feat: altered plan table
hngprojects/hng_boilerplate_java_web pull request #198
Opened 2024-07-27 20:07 UTC by Adewale66

## How this PR should be tested

The endpoint is protected and only a user with admin role can access it.

# new DB schema

```mermaid
erDiagram
    Plan {
        varchar(255) id PK
        varchar(255) name
        int price
        int duration
        varchar(255) description
        varchar(255) duration_unit
        varchar(255) features
    }
```

## How to test

- access route without being authenticated.
- create a plan with a user without admin role.
- create a plan that already exists.

### Checklist of what was implemented

- [x] Created endpoint (POST /api/v1/plans) to create new subscription plans.
- [x]  Validated creation of plans.
- [x]  Validated only users with admin roles can access
- [x] Wrote unit tests for creating plans.
- [x] Wrote unit tests for duplicate plan creation.

## Reference issue
[[FEAT] Implement API Endpoints for Creating Subscription Plans](https://github.com/hngprojects/hng_boilerplate_java_web/issues/6)

2024-07-27 23:27 UTC, Am0du submitted a review, later dismissed
LGTM

2024-07-28 16:33 UTC, lurldgbodex approved these changes

2024-07-28 16:41 UTC, lurldgbodex commented on src/main/resources/db/migration/V7.1__alter_plan_table.sql
> +ALTER TABLE plans
please check the application and update the version numbver

2024-07-28 16:48 UTC, lurldgbodex requested changes
check the app and update your version number to be a new later version number

2024-07-28 16:53 UTC, Adewale66 commented
The version number is correct, it avoids the mistake of using another number someone else has already used and it's just a table update @Am0du even agreed with it.

2024-07-28 18:05 UTC, lurldgbodex commented
There are newer version which has run on the database. when your application runs on the database, it will throw an error even though there is no 7.1 because of reference issue.You can try it on your local

2024-07-28 18:15 UTC, lurldgbodex approved these changes

2024-07-28 18:16 UTC, merged