Implement backend support for region selection
hngprojects/hng_boilerplate_java_web pull request #83
Opened 2024-07-21 21:03 UTC by unyimeudemy

# Implement Backend Functionality to Support the Region Selection Feature

## Description
Implement backend functionality to support the region selection feature.

## Acceptance Criteria
- Create a database schema to accommodate country preferences.
- Design and implement API endpoints for country selection.
- Implement validation and error handling for country-related inputs.

## Purpose
Provide backend infrastructure to manage and utilize user-selected country preferences within the application.

## Requirements
### Database Changes
Create a `regions` table to store available regions with fields such as `region_id`, `region_name`, `country_code`, `user_id`, and other relevant details.

### API Endpoints
- **GET /api/v1/regions/**: Fetch all available regions.
  - **Successful Response**
    ```json
    [
       {
          "region_code": "string",
          "region_name": "string",
          "status": "0",
          "created_on": "string", 
          "created_by": "string",
         "modified_on": "string", 
         "modified_by": "string"
       }
    ]
    ```

- **POST /api/v1/regions**: Assign a region to a user.
  - **Request Payload**
    ```json
    {  
      "user_id": "String(uuid)",
      "region_name": "String",
      "country_code": "String"
    }
    ```

- **GET /api/v1/regions/:user_id**: Retrieve the user's selected region.
  - **Successful Response**
    ```json
    { 
      "region_id": "Int",
      "user_id": "String(uuid)",
      "region_name": "String",
      "country_code": "String"
    }
    ```

- **PUT /api/v1/regions/:user_id**: Update the user's selected region.
  - **Request Payload**
    ```json
    { 
      "region_name": "String",
      "country_code": "String"
    }
    ```

  - **Failure Response**
    ```json
    { 
      "status_code": "String",
      "message": "String"
    }
    ```

### Business Logic
- Ensure the user's selected region is validated against the available regions.

### Authentication and Authorization
- Ensure that only authenticated users can update their region preferences.
- Implement necessary checks to ensure users can only update their own region.

### Validation
- Validate region selections to ensure they are within the predefined list of regions.

### Error Handling
- Handle scenarios where the region ID provided does not exist.
- Provide appropriate error messages for invalid region selections.

## Expected Outcome
- API endpoint allows users to select and update their preferred region.
- Users can successfully select and update their preferred region.
- The application can retrieve and utilize user-selected region preferences for personalized experiences.

## Database Model
### user_region
```
   {  
     "region_id": "Int", 
     "user_id": "String(uuid)", 
     "region_name": "String", 
     "region_code": "String' 
  }
```

2024-07-23 12:22 UTC, billmal071 approved these changes
LGTM

2024-07-24 16:16 UTC, NdubuisiJr requested changes

2024-07-24 16:16 UTC, NdubuisiJr commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
Do not check this in to github.

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/mappers/Mapper.java
> +public interface Mapper <A,B>{
Use better name than `A` and `B`

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/controller/RegionController.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/controller/RegionController.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/controller/RegionController.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/controller/RegionController.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/controller/RegionController.java
> +        //========== Ensure that assignee is owner of account. =================
Remove extra space and in-line comment.

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/controller/RegionController.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/controller/RegionController.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/controller/RegionController.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/controller/RegionController.java
> +//========== Ensure that only the current authenticated users can update their region preferences. ===============================================
Remove extra space and inline comments

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/dto/RegionDto.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/dto/UserRegionDto.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/entity/RegionEntity.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/entity/UserRegionEntity.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/repository/RegionRepository.java
> +
Remove extra spaces

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/repository/UserRegionRepository.java
> +
Remove extra space

2024-07-24 16:16 UTC, NdubuisiJr commented on src/main/java/hng_java_boilerplate/region/service/RegionService.java
> +// this comment is to check if ci cd test can be triggered.
Remove this comment

2024-07-24 17:14 UTC, unyimeudemy commented
@NdubuisiJr All unnecessary spaces have been removed

2024-07-24 20:02 UTC, NdubuisiJr approved these changes

2024-07-24 20:41 UTC, closed without merging